import Head from "next/head";
import Header from "./Header";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Payment Mania Mantap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col">
        <Header />
        <main className="mt-16 flex-grow bg-white p-4 dark:bg-primary">
          <div className="mx-auto w-full max-w-[1920px] min-h-screen">
            {children}
          </div>
        </main>
      </div>
    </>
  );
}
